---

- name: create R group
  group: 
    name: r
    state: present

- name: add users to group r
  when: users is defined and item.in_r|default(false)
  user:
    name: "{{ item.username }}"
    groups: r
    append: yes
  with_items:
    - "{{ users }}"

# - name: add docker key
#   apt_key:
#     keyserver: keyserver.ubuntu.com
#     id: E084DAB9

#- name: add R repository
#  apt_repository:
#    repo: deb http://mirrors.nic.cz/R/bin/linux/ubuntu/ artful/
#    state: present
