---
- hosts: all
  remote_user: root
  roles:
    - common
    - docker
    - emacs
    - r-base

- hosts: r
  remote_user: root
  roles:
    - r

- hosts: scala
  remote_user: root
  roles:
    - scala
