---

- name: create scala group
  group: 
    name: scala
    state: present

- name: add user to scala
  when: scala is defined
  user:
    name: "{{ item.username }}"
    groups: "{{ item.groups }} scala"
  with_items:
    - "{{ users|attr('is_scala') }}"

- name: install sbt (scala)
  when: scala is defined
  apt:
    deb: https://dl.bintray.com/sbt/debian/sbt-1.1.4.deb
    state: present

- name: create /var/lib/scala (scala)
  when: scala is defined
  file:
    path: /var/lib/scala
    group: scala
    recurse: yes
    mode: "g+rwx"
    stat: directory
